{
    "code": 200,
    "message": "success",
    "data": [{
            "name": "audio",
            "title": "音频管理",
            "icon": "layui-icon-senior",
            "list": [{
                "name": "Catalog",
                "title": "音频目录",
                "jump": "audio/catalogList"
            }]
        }, {
            "name": "broadcasting",
            "title": "电台管理",
            "icon": "layui-icon-console",
            "list": [{
                "name": "radioStation",
                "title": "电台列表",
                "jump": "radioStation/radioStationList"
            }, {
                "name": "radioStationAudio",
                "title": "添加音频",
                "jump": "radioStation/editRadioStation"
            }]
        }, {
            "name": "radioStation",
            "title": "动态管理",
            "icon": "layui-icon-console",
            "list": [{
                "name": "radioStation",
                "title": "动态列表",
                "jump": "content/dynamicList"
            }, {
                "name": "radioStationAudio",
                "title": "动态审核",
                "jump": "examine/dynamicList"
            }, {
                "name": "hotManage",
                "title": "热门规则",
                "jump": "dynamic/setDynamicRole"
            }]
        },
        {
            "name": "label",
            "title": "标签管理",
            "icon": "layui-icon-theme",
            "list": [{
                "name": "label",
                "title": "标签列表",
                "jump": "label/lableList"
            }]
        }, {
            "name": "classification",
            "title": "音频分类管理",
            "icon": "layui-icon-form",
            "list": [{
                "name": "classificationf",
                "title": "分类列表",
                "jump": "classification/classificationList"
            }]
        }, {
            "name": "user",
            "title": "用户管理",
            "icon": "layui-icon-user",
            "list": [{
                "name": "userList",
                "title": "用户列表",
                "jump": "user/user/userList"
            }, {
                "name": "examine",
                "title": "信息认证审核",
                "jump": "examine/informationList"
            }]
        }, {
            "name": "artist",
            "title": "艺人管理",
            "icon": "layui-icon-app",
            "list": [{
                "name": "artistList",
                "title": "艺人列表",
                "jump": "examine/artist"
            }, {
                "name": "actorExamine",
                "title": "艺人审核",
                "jump": "examine/artist"
            }]
        }, {
            "name": "comment",
            "title": "评论管理",
            "icon": "layui-icon-template-1",
            "list": [{
                "name": "comment-list",
                "title": "评论列表",
                "jump": "comment/commentList"
            }]
        }, {
            "name": "msg",
            "title": "消息管理",
            "icon": "layui-icon-dialogue",
            "list": [{
                "name": "message-add",
                "title": "新增消息",
                "jump": "message/newAddMessage"
            }, {
                "name": "administrators-list",
                "title": "消息列表",
                "jump": "message/list"
            }]
        }, {
            "name": "advertisement",
            "title": "广告管理",
            "icon": "layui-icon-read",
            "list": [{
                "name": "banner-list",
                "title": "首页轮播图",
                "jump": "advertisement/advertisementList"
            }, {
                "name": "banner-list",
                "title": "启动页广告",
                "jump": "advertisement/startAppAdv"
            }, {
                "name": "administrators-list",
                "title": "音频广告",
                "jump": "advertisement/audioAdv"
            }, {
                "name": "administrators-list",
                "title": "封面广告",
                "jump": "advertisement/dirAdv"
            }]
        }, {
            "name": "vip",
            "title": "VIP管理",
            "icon": "layui-icon-note",
            "list": [{
                "name": "payHistory",
                "title": "支付记录",
                "jump": "vip/payHistory"
            }, {
                "name": "vip",
                "title": "套餐管理",
                "jump": "vip/vipList"
            }, {
                "name": "secureIP",
                "title": "固定IP会员",
                "jump": "vip/secureIP"
            }]
        }, {
            "name": "finance",
            "title": "财务管理",
            "icon": "layui-icon-component",
            "list": [{
                "name": "finance",
                "title": "支付记录",
                "icon": "layui-icon-user",
                "jump": "finance/financeList"
            }]
        }, {
            "name": "useradmin",
            "title": "权限管理",
            "icon": "layui-icon-template",
            "list": [{
                "name": "useradmin",
                "title": "管理员管理",
                "jump": "useradmin/administratorsList"
            }, {
                "name": "useradmin",
                "title": "角色管理",
                "jump": "useradmin/roleList"
            }]
        }, {
            "name": "senior",
            "title": "系统管理",
            "icon": "layui-icon-set",
            "list": [{
                "name": "aboutUs",
                "title": "关于我们",
                "jump": "system/aboutUs"
            }, {
                "name": "feedback",
                "title": "意见反馈",
                "jump": "system/feedback"
            }, {
                "name": "echarts",
                "title": "常见问题",
                "jump": "system/problem"
            }, {
                "name": "administrators-rule",
                "title": "举报管理",
                "jump": "system/reportList"
            }, {
                "name": "task",
                "title": "任务管理",
                "jump": "task/taskList"
            }, {
                "name": "echarts",
                "title": "积分管理",
                "jump": "system/integralManager"
            }, {
                "name": "echarts",
                "title": "联系我们",
                "jump": "system/contactUs"
            }, {
                "name": "echarts",
                "title": "用户协议",
                "jump": "system/userAgreement"
            }]
        }
    ]
}